FROM python:3.9-slim

WORKDIR /app

COPY backend/api/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/api/main.py .

EXPOSE 8501

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8501"]
